### PR TITLE
Added spanish translation

### PR DESCRIPTION
**Pull request by alexander-ae**

### CODE REVIEW

**Comment by secnot** [comment]
Thanks 

I don't see a straight forward way of testing it, so I will need more time before merging.

**Comment by alexander-ae** [comment]
It seems to me that the "locale" files were not uploaded to pypi.

Maybe it's because the files need to be included in the MANIFEST.in?

https://pypi.python.org/pypi/django-isbn-field/0.5.1

**Comment by secnot** [comment]
Probably I'll fix it tomorrow

**Comment by secnot** [comment]
Just uploaded the new version to pypi.

**Comment by alexander-ae** [comment]
this time the translations work correctly. Thank you very much

**Comment by secnot** [comment]
I'm glad to be of assistance :smile:

**Pull request merged**
