### PR TITLE
Reproducable test setup, travis ci configuration, improved validation logic

### PR DESCRIPTION
**Pull request by codeZeilen**
This is a huge pull request so let me explain every part in detail.

1) When I tried to change something in this project I had a hard time setting it up. Hence, I added a tox.ini, a settings.py, re-added the manage.py

2.) With the improved testing setup, I also just added a travis-ci configuration to guarantee test execution

3.) The validation of the field was way to strict. The ISO standard for ISBNs allows for spaces or dashes to be separators in ISBNs which the validation did not allow so far. Consequently, the limitations for the Field had to be changed.

### CODE REVIEW

**Comment by codeZeilen** [comment]
btw: The travis build is here: 
https://travis-ci.org/codeZeilen/django-isbn-field/builds/259924649

**Comment by secnot** [comment]
Great job adding all the test infrastructure, I'll merge the pull request soon. There is just one problem.

With the field validation the idea was to force the users to input all the ISBNs using the same format, so as to not store a mix of formats into the DB making it safe by default. The other option was to clean the ISBN before storing, but I'm not a fan to changing user inputs.

With your approach I'm sure many new projects will find a mess in the DB until they clean the inputs, but as you say it follows the standard, and this is the second problem with too restrictive validation in a short time.

Perhaps adding a warning to the README about cleaning the ISBN is enough, the alternative is an extra keyword for the model field (**e.g.**  *normalize_isbn*) to enable/disable removing spaces and dashes before committing (enabled by default for backwards compatibility).

I think cleaning the field is safest, but truth be told, I'm not working on anything related at the moment and just a warning is tempting.

**Comment by codeZeilen** [comment]
Sorry for not coming back to this. I am currently busy with a trip and will
look into this in the week from the 28th :)

secnot <notifications@github.com> schrieb am Mi., 2. Aug. 2017 um 00:05 Uhr:

**Comment by secnot** [comment]
Ok, I have had a little free time to merge the pull request and fix the field.

- Added upper case validation to **ISBNValidator**
- New *clean_isbn* option for **ISBNField** to remove spaces/dashes before saving
- Rearranged tests to make easier testing ISBNField.

Everything seems to be working fine, but  currently I don't have any site where I can test the field more thorougly, so if you don't find any new bug I will upload a new version to pypi in a week or two.

**Pull request merged**
