### PR TITLE
if field is blank=True, the replace fail

### PR DESCRIPTION
**Pull request by ignacionf**
If field is None, the replace fail.

This prevent the exception.

### CODE REVIEW

**Comment by secnot** [comment]
Apologies for the delay I didn't see the message for the pull request.

If I understand correctly the exception is raised when no value is provided by the user and blank is allowed. In that case the form returns None and if cleaning is enabled the exception is raised

I just need a few tests before merging, I thought that the default value for blank fields was an empty string.

**Comment by secnot** [comment]
Hi, there is a fix in develop branch including tests, if you could test it in your app before uploading a new version it would be great.

**Comment by ignacionf** [comment]
Oka, i will test #develop in my app. Tnks!

**Comment by ignacionf** [comment]
Test OK. Your solution is cleaner than mine, i shall use when you merge with master.

**Comment by secnot** [comment]
Thanks for testing it, I will upload to pypi as soon as the spanish translation is merged and tested.

**Comment by secnot** [comment]
New version uploaded to pypi.

**Pull request closed without merging**
